DROP DATABASE IF EXISTS DBCRUDUSUARIOS;
CREATE DATABASE DBCRUDUSUARIOS;
USE DBCRUDUSUARIOS;

CREATE TABLE NIVEL (
	 IDNIVEL INT NOT NULL PRIMARY KEY AUTO_INCREMENT
     , DESCRICAO VARCHAR (100)
);

CREATE TABLE USUARIOVO (
	IDUSUARIOVO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , NOME VARCHAR (100)
    , EMAIL VARCHAR (45)
    , SENHA VARCHAR (20)
    , NIVEL INT NOT NULL 
    , FOREIGN KEY (IDNIVEL) REFERENCES NIVEL (IDNIVEL)
);